language: node_js
node_js:
  - "4.2"
services: mongodb
before_script:
  - mongo featureguardian
script:
  - npm install
  - npm test
  - mocha integration-test/bootstrap.test.js integration-test/*.test.js
notifications:
  slack: featureguardian:ZbWTsXjCSfkOBLmoJtKw3psU
